In [47]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split as tts

In [48]:
df= pd.read_csv("loan_approval_dataset.csv")

In [49]:
df.drop_duplicates()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4264,4265,5,Graduate,Yes,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected
4265,4266,0,Not Graduate,Yes,3300000,11300000,20,559,4200000,2900000,11000000,1900000,Approved
4266,4267,2,Not Graduate,No,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected
4267,4268,1,Not Graduate,No,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved
4268,4269,1,Graduate,No,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved

In [50]:
df.isnull().sum()

loan_id                      0
 no_of_dependents            0
 education                   0
 self_employed               0
 income_annum                0
 loan_amount                 0
 loan_term                   0
 cibil_score                 0
 residential_assets_value    0
 commercial_assets_value     0
 luxury_assets_value         0
 bank_asset_value            0
 loan_status                 0
dtype: int64

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   loan_id                    4269 non-null   int64
 1    no_of_dependents          4269 non-null   int64
 2    education                 4269 non-null   object
 3    self_employed             4269 non-null   object
 4    income_annum              4269 non-null   int64
 5    loan_amount               4269 non-null   int64
 6    loan_term                 4269 non-null   int64
 7    cibil_score               4269 non-null   int64
 8    residential_assets_value  4269 non-null   int64
 9    commercial_assets_value   4269 non-null   int64
 10   luxury_assets_value       4269 non-null   int64
 11   bank_asset_value          4269 non-null   int64
 12   loan_status               4269 non-null   object
dtypes: int64(10), object(3)
memory usage: 433.7+ KB

In [52]:
df.describe()

,loan_id,no_of_dependents,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
count,4269.000000,4269.000000,4.269000e+03,4.269000e+03,4269.000000,4269.000000,4.269000e+03,4.269000e+03,4.269000e+03,4.269000e+03
mean,2135.000000,2.498712,5.059124e+06,1.513345e+07,10.900445,599.936051,7.472617e+06,4.973155e+06,1.512631e+07,4.976692e+06
std,1232.498479,1.695910,2.806840e+06,9.043363e+06,5.709187,172.430401,6.503637e+06,4.388966e+06,9.103754e+06,3.250185e+06
min,1.000000,0.000000,2.000000e+05,3.000000e+05,2.000000,300.000000,-1.000000e+05,0.000000e+00,3.000000e+05,0.000000e+00
25%,1068.000000,1.000000,2.700000e+06,7.700000e+06,6.000000,453.000000,2.200000e+06,1.300000e+06,7.500000e+06,2.300000e+06
50%,2135.000000,3.000000,5.100000e+06,1.450000e+07,10.000000,600.000000,5.600000e+06,3.700000e+06,1.460000e+07,4.600000e+06
75%,3202.000000,4.000000,7.500000e+06,2.150000e+07,16.000000,748.000000,1.130000e+07,7.600000e+06,2.170000e+07,7.100000e+06
max,4269.000000,5.000000,9.900000e+06,3.950000e+07,20.000000,900.000000,2.910000e+07,1.940000e+07,3.920000e+07,1.470000e+07

In [53]:
df.columns

Index(['loan_id', ' no_of_dependents', ' education', ' self_employed',
       ' income_annum', ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

In [87]:
from sklearn.preprocessing import LabelEncoder
Encoder = LabelEncoder()
df[' education'] = Encoder.fit_transform(df[' education'])
df[' self_employed'] = Encoder.fit_transform(df[' self_employed'])

In [94]:
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [89]:
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [ ]:
from sklearn.ensemble import RandomForestClassifier as rfc

In [96]:
x=df.iloc[:,:-1]

In [97]:
x

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000
...,...,...,...,...,...,...,...,...,...,...,...
4264,5,0,1,1000000,2300000,12,317,2800000,500000,3300000,800000
4265,0,1,1,3300000,11300000,20,559,4200000,2900000,11000000,1900000
4266,2,1,0,6500000,23900000,18,457,1200000,12400000,18100000,7300000
4267,1,1,0,4100000,12800000,8,780,8200000,700000,14100000,5800000
4268,1,0,0,9200000,29700000,10,607,17800000,11800000,35700000,12000000

In [98]:
y=df.iloc[:,-1]

In [99]:
y

0        Approved
1        Rejected
2        Rejected
3        Rejected
4        Rejected
          ...
4264     Rejected
4265     Approved
4266     Rejected
4267     Approved
4268     Approved
Name:  loan_status, Length: 4269, dtype: object

In [100]:
x_train,x_test,y_train,y_test=tts(x,y,test_size=.25,random_state=50)

In [101]:
x_train

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
500,2,0,0,200000,700000,8,851,400000,200000,800000,200000
3690,0,0,1,5800000,21800000,2,561,4400000,7200000,15000000,4200000
2952,4,1,0,7900000,31500000,20,386,14300000,3800000,23800000,7500000
431,1,0,0,1100000,3500000,8,562,2300000,1200000,3200000,500000
1165,1,1,1,5400000,20700000,8,753,1900000,800000,19000000,3600000
...,...,...,...,...,...,...,...,...,...,...,...
3330,1,0,0,6300000,17200000,12,714,10100000,4200000,24700000,8500000
70,4,1,1,500000,1500000,20,340,100000,200000,1900000,600000
132,3,1,1,1800000,3600000,18,465,600000,500000,5400000,2600000
2014,4,0,1,8800000,34200000,16,844,18700000,11000000,20700000,10700000
1931,3,0,0,6300000,17000000,16,388,11700000,2100000,16100000,3200000

In [110]:
model= rfc(n_estimators=70, criterion='gini')

In [111]:
model.fit(x_train,y_train)

RandomForestClassifier(n_estimators=70)

In [112]:
y_pred=model.predict(x_test)
y_pred

array([' Rejected', ' Rejected', ' Rejected', ..., ' Approved',
       ' Rejected', ' Approved'], dtype=object)

In [113]:
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix, precision_score

In [114]:
confusion_matrix(y_test, y_pred)

array([[664,   5],
       [ 15, 384]])

In [115]:
accuracy_score(y_test, y_pred)

0.9812734082397003

In [116]:
import joblib

In [117]:
joblib.dump(model, 'Loan.pkl')

['Loan.pkl']

In [118]:
joblib.load('Loan.pkl')

RandomForestClassifier(n_estimators=70)